### ISSUE TITLE
Adding Item to Cart Issue

### ISSUE THREAD

**Issue by ankitkayastha** [sunnyownage/Inventory-FrontEnd#111]
As a User, my cart is empty which is fine, but when i try to edit the quantity of an item to add to the cart, the buttons appear oddly. The picture is below:

![image](https://cloud.githubusercontent.com/assets/6867057/23377289/755f6d26-fcfd-11e6-9b49-736a89b367ad.png)

My theory is that it occurs for items that have been previously added to a cart. In other words, let's say I add item A to a shopping cart and send the shopping cart successfully. If i try to add Item A again to a new cart, it seems to show both the Update and Add to Cart Buttons.

Update:
When I click on Update quantity, I get an alert saying Not found (picture shown below). I think it's because even though the old cart is gone, it still thinks that item is part of the old cart so both buttons show. If i were to click add to cart instead of Update quantity, then i think it would work. But I have a feeling /getActive is not being called/being called in the right place.

**Comment by andrewssun1** [comment]
W T F

**Comment by andrewssun1** [comment]
omg this bug makes no sense I am definitely getting the active cart
