### ISSUE TITLE
Allow managers to configure loan reminder emails

### ISSUE THREAD

**Issue by pht5** [sunnyownage/Inventory-FrontEnd#130]
10.4. Managers shall be able to configure “loan reminder emails”.
10.4.1. Managers shall be able to configure on which dates emails will be sent.
10.4.2. Managers shall be able to configure a body of text to be prepended in the body of
this email.
10.6. To allow users to filter emails from the system easily, managers shall be able to configure
a “subject tag”: a small piece of text to be prepended to the subject line of all emails
sent by the system.

**Comment by ankitkayastha** [comment]
https://github.com/nesh170/asap-inventory-system/pull/205
