### ISSUE TITLE
Add Bulk Import Button/File Chooser

### ISSUE THREAD

**Issue by pht5** [sunnyownage/Inventory-FrontEnd#131]
9. Bulk import facility
9.1. Administrators shall be able to import new distinct items into the database by means
of a text-based import based on a simple format such as CSV, JSON, XML, or another
plaintext-based format.
9.2. The import interface shall include documentation as to the import format.
9.3. The import action shall only occur if the entire input is free of name conflicts or otherwise
problematic issues; if such issues arise, the precise nature of the error should be presented
to the administrator in enough detail that it can be corrected.

**Comment by nesh170** [comment]
https://github.com/nesh170/asap-inventory-system/pull/175

**Comment by nesh170** [comment]
https://drive.google.com/open?id=0B1BirZXBsYBaWG9hd1A0WjJ2RkE

for CSV file
