### ISSUE TITLE
Alert notification for when updating information for an asset (like serial number and location)

### ISSUE THREAD

**Issue by ankitkayastha** [sunnyownage/Inventory-FrontEnd#200]
Also would it be possible to make the modal redirect to the item detailed view instead of back to the asset detailed view. Once I edit an asset, I would have to click the cancel button once I finish editing - feel like it would be easier to just direct back to the item detailed view.

**Comment by pht5** [comment]
Errors already handled. Success: too hard to be worth it due to the way custom fields have to be saved (because the back-end forces us to do this with many api calls). And the sidenote I disagree with.

**Comment by pht5** [comment]
Your confirmation that the save was successful is that you see the changes right away
