### ISSUE TITLE
When logging additional instances/destruction of instances, comment field should not be required.

### ISSUE THREAD

**Issue by ankitkayastha** [sunnyownage/Inventory-FrontEnd#205]

**Comment by nesh170** [comment]
![image](https://cloud.githubusercontent.com/assets/8827344/25104678/3e68fc20-238f-11e7-96ec-0ec7399150e3.png)

As noticed, the button is shaded so it is not functional. 
In addition, remove help text and don't allow -ve numbers

**Comment by nesh170** [comment]
https://github.com/sunnyownage/Inventory-FrontEnd/pull/207
