### ISSUE TITLE
Various Bugs

### ISSUE THREAD

**Issue by andrewssun1** [sunnyownage/Inventory-FrontEnd#35]
-Tables needs to update when actions occur
-Every time a tab is loaded, the component should reload
-When more items are deleted such that the last pagination page is not needed, that page needs to be deleted

**Comment by andrewssun1** [comment]
all tables should update when actions occur and tab is loaded, still need to look at last point

**Comment by nesh170** [comment]
Updating quantity in the disbursement cart  page does not display error when trying to disburse more than avaliable
![image](https://cloud.githubusercontent.com/assets/8827344/23345426/fd5c7eb4-fc5b-11e6-889d-5017c0b9abb8.png)

There are only 2 Name Here
