### ISSUE TITLE
Requests Filtering by Status

### ISSUE THREAD

**Issue by ankitkayastha** [sunnyownage/Inventory-FrontEnd#82]
I filtered requests by status (let's say to outstanding). When I click on a different tab (such as items) and then back on the Requests tab, it shows all of the requests even though the filter still says outstanding. I think this is a similar issue to the previous one (https://github.com/sunnyownage/Inventory-FrontEnd/issues/78).

**Comment by andrewssun1** [comment]
ty patrick
